#!/bin/sh
# tools/syncaddon.sh -- sync the headless engine into the DEV addon, or prove
# the copies still match. M5 part 1.
#
#   sh tools/syncaddon.sh            copy engine files into the addon folder,
#                                    regenerate the derived HandLog.lua, then
#                                    run the loadtest
#   sh tools/syncaddon.sh --check    exit non-zero if any addon copy differs
#                                    byte-for-byte from the headless original
#                                    (or the derived file from its sources, or
#                                    the .toc load order no longer loads)
#
# THE DIRECTION IS ONE-WAY AND THIS SCRIPT IS WHAT ENFORCES IT. The headless
# tree (dev/idlebattle/) is the single source of truth: it is where the engine
# is edited, gated (ci.sh / m2.sh / m3.sh / m4.sh) and golden-checked. The
# addon folder (dev/PengyouGamesDev/IdleBattle/) holds byte-identical copies
# because a .toc may not contain ".." -- an addon folder has to be
# self-contained, so the sim has to exist twice (the arcade's mkaddon.sh makes
# the same argument). An edit made in the addon copy is a second, untested
# copy of the game that no gate reads; --check turns that state into a red
# build instead of a silent fork. NEVER edit the copies; edit the originals
# and re-run this script.
#
# WHAT IS SYNCED. Exactly the files the M5 addon needs:
#   sim/Rules.lua sim/Rand.lua sim/Hash.lua sim/Sim.lua sim/Mods.lua
#   net/Wire.lua  net/Net.lua  net/Snap.lua
# NOT net/Transport.lua (the fake M4 channel -- the addon's channel is real),
# NOT fog/Fog.lua (render filter, M7), NOT policy/ sweep/ harness/ (headless
# tooling). One file is DERIVED rather than copied: IdleBattle/HandLog.lua is
# generated from harness/logs/hand.iblog plus the three committed goldens in
# harness/selftest.lua, so the in-game selftest asserts the exact numbers the
# headless tree commits -- written down once, extracted here, never hand-copied.
#
# THE LOADTEST. WoW loads the engine block of PengyouGamesDev.toc in
# dependency order (each file's imports resolve at file scope through
# IB_SIM_MODULES; see IdleBattle/Loader.lua). This script re-executes that
# exact order headless with require() disabled, asserts every module
# registered, then replays the hand log and compares all three goldens -- so a
# broken .toc order, a missing registration tail, or a drifted copy fails HERE
# rather than at login.

set -u

here="$(cd "$(dirname "$0")/.." && pwd)"     # dev/idlebattle
addon="$(cd "$here/../PengyouGamesDev" 2>/dev/null && pwd)"
if [ -z "$addon" ]; then
  echo "syncaddon: cannot find dev/PengyouGamesDev beside dev/idlebattle" >&2
  exit 2
fi
dst="$addon/IdleBattle"
toc="$addon/PengyouGamesDev.toc"
LUA="${LUA:-/opt/homebrew/bin/lua}"
command -v "$LUA" >/dev/null 2>&1 || LUA=lua

# The synced file list, in the addon's dependency (.toc) order. ONE list: the
# copy step, the check step and the loadtest all read this.
FILES="sim/Hash.lua sim/Rand.lua sim/Mods.lua sim/Rules.lua sim/Sim.lua net/Wire.lua net/Snap.lua net/Net.lua"

mode="sync"
[ "${1:-}" = "--check" ] && mode="check"

fail=0

# ---------------------------------------------------------------------------
# derived file: HandLog.lua from hand.iblog + the selftest goldens
# ---------------------------------------------------------------------------

gen_handlog() {
  out="$1"
  iblog="$here/harness/logs/hand.iblog"
  st="$here/harness/selftest.lua"
  if [ ! -f "$iblog" ] || [ ! -f "$st" ]; then
    echo "syncaddon: missing $iblog or $st" >&2
    return 1
  fi
  g_rules=$(awk '/^local GOLDEN_RULESHASH = /{print $4; exit}' "$st")
  g_state=$(awk '/^local GOLDEN_STATE = /{print $4; exit}' "$st")
  g_digest=$(awk '/^local GOLDEN_LOGDIGEST = /{print $4; exit}' "$st")
  # each extraction checked SEPARATELY: the concatenated form let exactly one
  # empty extraction slip through as long as the other two were digits (the
  # broken HandLog then failed only downstream, in the loadtest) -- M5 review
  for gv in "$g_rules" "$g_state" "$g_digest"; do
    case "$gv" in
      *[!0-9]*|"")
        echo "syncaddon: could not extract all three GOLDEN_ constants from harness/selftest.lua (rules='$g_rules' state='$g_state' digest='$g_digest')" >&2
        return 1 ;;
    esac
  done
  awk -v grules="$g_rules" -v gstate="$g_state" -v gdigest="$g_digest" '
    BEGIN {
      print "-- IdleBattle/HandLog.lua - GENERATED by dev/idlebattle/tools/syncaddon.sh."
      print "-- DO NOT EDIT. Derived from dev/idlebattle/harness/logs/hand.iblog plus the"
      print "-- committed goldens in dev/idlebattle/harness/selftest.lua, so the in-game"
      print "-- selftest (/pgd ib selftest) asserts the exact numbers the headless tree"
      print "-- commits. syncaddon.sh --check fails if this file drifts from its sources."
      print "local ADDON, PG = ..."
      print ""
      print "local M = {"
      seed = ""; ticks = ""; l1 = ""; l2 = ""; ncmd = 0
    }
    /^seed /   { seed = $2 }
    /^ticks /  { ticks = $2 }
    /^loadout 1 / { l1 = $3 ", " $4 ", " $5 ", " $6 ", " $7 }
    /^loadout 2 / { l2 = $3 ", " $4 ", " $5 ", " $6 ", " $7 }
    /^cmd /    { ncmd = ncmd + 1
                 cmds[ncmd] = "    { exec = " $2 ", side = " $3 ", seq = " $4 \
                   ", kind = \"" $5 "\", target = " $6 ", count = " $7 \
                   ", arrive = " $8 " }," }
    END {
      print "  seed = " seed ","
      print "  ticks = " ticks ","
      print "  loadout1 = { " l1 " },"
      print "  loadout2 = { " l2 " },"
      print "  goldenRulesHash = " grules ","
      print "  goldenState = " gstate ","
      print "  goldenLogDigest = " gdigest ","
      print "  cmds = {"
      for (i = 1; i <= ncmd; i++) print cmds[i]
      print "  },"
      print "}"
      print ""
      print "local IB_REG = rawget(_G, \"IB_SIM_MODULES\")"
      print "if IB_REG then IB_REG.HandLog = M end"
      print ""
      print "return M"
    }
  ' "$iblog" > "$out"
}

# ---------------------------------------------------------------------------
# loadtest: execute the .toc engine order headless, require() disabled
# ---------------------------------------------------------------------------

loadtest() {
  tocorder=$(awk '/^IdleBattle\\/{ gsub(/\\/, "/"); gsub(/\r/, ""); print }' "$toc")
  if [ -z "$tocorder" ]; then
    echo "syncaddon: no IdleBattle\\ lines in $toc" >&2
    return 1
  fi
  first=$(printf '%s\n' "$tocorder" | head -1)
  if [ "$first" != "IdleBattle/Loader.lua" ]; then
    echo "syncaddon: the first IdleBattle line of the .toc must be Loader.lua (it creates IB_SIM_MODULES); got $first" >&2
    return 1
  fi
  lt=$(mktemp "${TMPDIR:-/tmp}/ibloadtest.XXXXXX") || return 1
  cat > "$lt" <<'EOF'
-- generated loadtest chunk: emulate the WoW load of the IdleBattle block.
local addon, order = (...), select(2, ...)
_G.IB_SIM_MODULES = {}          -- what IdleBattle/Loader.lua does at file scope
require = nil                    -- WoW has none: any fallback import must die here
local names = {}
for name in string.gmatch(order, "[^\n]+") do names[#names + 1] = name end
for i = 2, #names do             -- 1 is Loader.lua, emulated above
  local chunk, err = loadfile(addon .. "/" .. names[i])
  if not chunk then error("loadtest: " .. tostring(err), 0) end
  chunk("PengyouGamesDev", {})   -- the (ADDON, PG) varargs WoW passes
end
local E = _G.IB_SIM_MODULES
local mods = { "Hash", "Rand", "Mods", "Rules", "Sim", "Wire", "Snap", "Net", "HandLog" }
for i = 1, #mods do
  if not E[mods[i]] then error("loadtest: " .. mods[i] .. " never registered into IB_SIM_MODULES", 0) end
end
-- the in-game selftest's own arithmetic, proven at sync time
local L = E.HandLog
local sim = E.Sim.new(E.Rules, L.seed, L.loadout1, L.loadout2)
for i = 1, #L.cmds do
  local c = L.cmds[i]
  local ok, err = sim:queueCommand({ side = c.side, seq = c.seq, tick = c.exec,
                                     kind = c.kind, target = c.target, count = c.count })
  if not ok then error("loadtest: hand log atom " .. i .. " refused: " .. tostring(err), 0) end
end
while sim.clock < L.ticks do
  if not sim:tick() then break end
end
local state, digest = E.Hash.state(sim), E.Hash.log(sim)
if E.Rules.rulesHash ~= L.goldenRulesHash then
  error("loadtest: rulesHash " .. E.Rules.rulesHash .. " want " .. L.goldenRulesHash, 0)
end
if state ~= L.goldenState then
  error("loadtest: stateHash " .. state .. " want " .. L.goldenState, 0)
end
if digest ~= L.goldenLogDigest then
  error("loadtest: logDigest " .. digest .. " want " .. L.goldenLogDigest, 0)
end
print("  loadtest: .toc order loads, all 9 modules registered, hand log reproduces the goldens")
EOF
  "$LUA" "$lt" "$addon" "$tocorder"
  rc=$?
  rm -f "$lt"
  return $rc
}

# ---------------------------------------------------------------------------
# sync / check
# ---------------------------------------------------------------------------

if [ "$mode" = "sync" ]; then
  mkdir -p "$dst/sim" "$dst/net" || exit 2
  for f in $FILES; do
    cp "$here/$f" "$dst/$f" || { echo "syncaddon: copy failed for $f" >&2; exit 2; }
  done
  gen_handlog "$dst/HandLog.lua" || exit 2
  echo "syncaddon: synced $(echo $FILES | wc -w | tr -d ' ') engine files + HandLog.lua into $dst"
else
  for f in $FILES; do
    if [ ! -f "$dst/$f" ]; then
      echo "syncaddon CHECK: MISSING addon copy $f" >&2
      fail=1
    elif ! cmp -s "$here/$f" "$dst/$f"; then
      echo "syncaddon CHECK: $f DIFFERS from the headless original -- edit dev/idlebattle/$f and re-sync, never the copy" >&2
      fail=1
    fi
  done
  tmp=$(mktemp "${TMPDIR:-/tmp}/ibhandlog.XXXXXX") || exit 2
  if gen_handlog "$tmp"; then
    if [ ! -f "$dst/HandLog.lua" ]; then
      echo "syncaddon CHECK: MISSING derived file IdleBattle/HandLog.lua" >&2
      fail=1
    elif ! cmp -s "$tmp" "$dst/HandLog.lua"; then
      echo "syncaddon CHECK: HandLog.lua DIFFERS from its sources (hand.iblog / selftest goldens) -- re-run syncaddon.sh" >&2
      fail=1
    fi
  else
    fail=1
  fi
  rm -f "$tmp"
fi

if [ $fail -eq 0 ]; then
  loadtest || fail=1
fi

if [ $fail -ne 0 ]; then
  echo "syncaddon: RED" >&2
  exit 1
fi
echo "syncaddon: GREEN ($mode)"
