-- IdleBattle/HandLog.lua - GENERATED by dev/idlebattle/tools/syncaddon.sh.
-- DO NOT EDIT. Derived from dev/idlebattle/harness/logs/hand.iblog plus the
-- committed goldens in dev/idlebattle/harness/selftest.lua, so the in-game
-- selftest (/pgd ib selftest) asserts the exact numbers the headless tree
-- commits. syncaddon.sh --check fails if this file drifts from its sources.
local ADDON, PG = ...

local M = {
  seed = 4242,
  ticks = 260,
  loadout1 = { 0, 0, 0, 0, 0 },
  loadout2 = { 0, 0, 0, 0, 0 },
  goldenRulesHash = 767294897,
  goldenState = 1939244196,
  goldenLogDigest = 1455081792,
  cmds = {
    { exec = 20, side = 1, seq = 1, kind = "S", target = 1, count = 1, arrive = 5 },
    { exec = 20, side = 2, seq = 1, kind = "S", target = 1, count = 1, arrive = 12 },
  },
}

local IB_REG = rawget(_G, "IB_SIM_MODULES")
if IB_REG then IB_REG.HandLog = M end

return M
